baseURL = "https://tailwind-elements.com/"
languageCode = "en-us"
title = "Tailwind Elements - Bootstrap components recreated with Tailwind"
theme = "ga-hugo-theme"
enableInlineShortcodes = "true"
custom_css = ["css/custom.css"]

# NODE_ENV=production hugo
